from __future__ import annotations

EVENT_TYPES = [
    "earnings_report",
    "revenue_growth",
    "revenue_decline",
    "profit_growth",
    "profit_decline",
    "guidance_update",
    "analyst_upgrade",
    "analyst_downgrade",
    "price_target_change",
    "product_launch",
    "partnership",
    "merger_acquisition",
    "lawsuit",
    "regulatory_investigation",
    "executive_change",
    "layoffs",
    "dividend_announcement",
    "share_buyback",
    "debt_financing",
    "stock_split",
    "macroeconomic_event",
    "supply_chain_event",
    "recession_inflation_interest_rate",
    "options_activity",
    "portfolio_holding",
    "stock_performance",
    "market_cap_milestone",
    "business_segment_performance",
    "market_share",
    "competitive_position",
    "market_commentary",
    "valuation_multiple",
    "balance_sheet",
    "cash_flow",
    "analyst_estimate",
    "capital_allocation",
    "price_level_range",
    "other",
]

EVENT_TYPE_ALIASES = {
    "stock_return": "stock_performance",
    "stock_price_return": "stock_performance",
    "share_price_return": "stock_performance",
    "share_return": "stock_performance",
    "market_cap": "market_cap_milestone",
    "market_cap_growth": "market_cap_milestone",
    "market_cap_grow": "market_cap_milestone",
    "market_cap_increase": "market_cap_milestone",
    "geographic_expansion": "business_segment_performance",
    "geographic_scale": "business_segment_performance",
    "price_target": "price_target_change",
    "price_targets": "price_target_change",
    "analyst_price_target": "price_target_change",
    "target_price": "price_target_change",
    "consensus_price_target": "price_target_change",
    "average_price_target": "price_target_change",
    "upside_target": "price_target_change",
    "capital_spending": "capital_allocation",
    "capital_expenditure": "capital_allocation",
    "capital_expenditures": "capital_allocation",
    "investment_spending": "capital_allocation",
    "cost_reduction": "capital_allocation",
    "cost_savings": "capital_allocation",
    "share_repurchase": "share_buyback",
    "pe_ratio": "valuation_multiple",
    "p_e_ratio": "valuation_multiple",
    "price_to_earnings": "valuation_multiple",
    "forward_pe": "valuation_multiple",
    "valuation": "valuation_multiple",
    "valuation_ratio": "valuation_multiple",
    "price_to_book": "valuation_multiple",
    "ev_ebitda": "valuation_multiple",
    "free_cash_flow": "cash_flow",
    "fcf": "cash_flow",
    "operating_cash_flow": "cash_flow",
    "cash_burn": "cash_flow",
    "debt": "balance_sheet",
    "debt_level": "balance_sheet",
    "long_term_debt": "balance_sheet",
    "net_debt": "balance_sheet",
    "cash_position": "balance_sheet",
    "leverage": "balance_sheet",
    "liquidity": "balance_sheet",
    "earnings_estimate": "analyst_estimate",
    "consensus_estimate": "analyst_estimate",
    "eps_estimate": "analyst_estimate",
    "estimate_revision": "analyst_estimate",
    "52_week_range": "price_level_range",
    "price_range": "price_level_range",
    "stock_price_level": "price_level_range",
}

DEFAULT_ANCHOR_COMPANIES = {
    "T": {
        "company": "AT&T",
        "aliases": ["AT&T", "AT&T Inc.", "AT&T Corporation", "AT&T Corp.", "AT and T"],
    },
    "INTC": {
        "company": "Intel",
        "aliases": ["Intel", "Intel Corporation", "Intel Corp."],
    },
    "AMD": {
        "company": "Advanced Micro Devices",
        "aliases": ["AMD", "Advanced Micro Devices", "Advanced Micro Devices Inc."],
    },
    "CVX": {
        "company": "Chevron",
        "aliases": ["Chevron", "Chevron Corporation", "Chevron Corp."],
    },
    "BABA": {
        "company": "Alibaba",
        "aliases": ["Alibaba", "Alibaba Group", "Alibaba Group Holding", "Alibaba Group Holding Limited"],
    },
}

TEXT_AMBIGUOUS_ANCHOR_TICKERS = {"T"}

ANCHOR_IMPACT_TYPES = [
    "direct",
    "competitor",
    "supplier_customer",
    "partner",
    "peer_comparison",
    "ecosystem",
    "portfolio",
    "macro",
    "regulatory",
    "market_sentiment",
    "mentioned",
    "other",
]

ANCHOR_IMPACT_DIRECTIONS = ["positive", "negative", "neutral"]

ANCHOR_IMPACT_DIRECTION_SCORE = {
    "positive": 1.0,
    "negative": -1.0,
    "neutral": 0.1,
}

EVENT_COMPANY_EDGE_BY_TYPE = {
    "earnings_report": "REPORTS_EARNINGS_FOR",
    "revenue_growth": "REVENUE_GROWTH_FOR",
    "revenue_decline": "REVENUE_DECLINE_FOR",
    "profit_growth": "PROFIT_GROWTH_FOR",
    "profit_decline": "PROFIT_DECLINE_FOR",
    "guidance_update": "UPDATES_GUIDANCE_FOR",
    "analyst_upgrade": "ANALYST_UPGRADE_FOR",
    "analyst_downgrade": "ANALYST_DOWNGRADE_FOR",
    "price_target_change": "PRICE_TARGET_CHANGE_FOR",
    "product_launch": "PRODUCT_LAUNCH_BY",
    "partnership": "PARTNERSHIP_INVOLVES",
    "merger_acquisition": "MERGER_ACQUISITION_INVOLVES",
    "lawsuit": "LEGAL_RISK_FOR",
    "regulatory_investigation": "REGULATORY_RISK_FOR",
    "executive_change": "EXECUTIVE_CHANGE_AT",
    "layoffs": "LAYOFFS_AT",
    "dividend_announcement": "DIVIDEND_ANNOUNCEMENT_FOR",
    "share_buyback": "SHARE_BUYBACK_FOR",
    "debt_financing": "DEBT_FINANCING_FOR",
    "stock_split": "STOCK_SPLIT_FOR",
    "macroeconomic_event": "MACRO_IMPACT_ON",
    "supply_chain_event": "SUPPLY_CHAIN_IMPACT_ON",
    "recession_inflation_interest_rate": "MACRO_RATE_IMPACT_ON",
    "options_activity": "OPTIONS_ACTIVITY_FOR",
    "portfolio_holding": "PORTFOLIO_HOLDING_OF",
    "stock_performance": "STOCK_PERFORMANCE_FOR",
    "market_cap_milestone": "MARKET_CAP_MILESTONE_FOR",
    "business_segment_performance": "BUSINESS_SEGMENT_PERFORMANCE_FOR",
    "market_share": "MARKET_SHARE_CHANGE_FOR",
    "competitive_position": "COMPETITIVE_POSITION_FOR",
    "market_commentary": "MARKET_COMMENTARY_MENTIONS",
    "valuation_multiple": "VALUATION_MULTIPLE_FOR",
    "balance_sheet": "BALANCE_SHEET_FOR",
    "cash_flow": "CASH_FLOW_FOR",
    "analyst_estimate": "ANALYST_ESTIMATE_FOR",
    "capital_allocation": "CAPITAL_ALLOCATION_BY",
    "price_level_range": "PRICE_LEVEL_FOR",
    "other": "EVENT_INVOLVES_COMPANY",
}

ANCHOR_IMPACT_EDGE_BY_TYPE = {
    "direct": "DIRECTLY_IMPACTS_ANCHOR",
    "competitor": "COMPETES_WITH_ANCHOR",
    "supplier_customer": "SUPPLY_CUSTOMER_IMPACT_ON_ANCHOR",
    "partner": "PARTNERS_WITH_ANCHOR",
    "peer_comparison": "PEER_COMPARED_WITH_ANCHOR",
    "ecosystem": "ECOSYSTEM_IMPACT_ON_ANCHOR",
    "portfolio": "PORTFOLIO_EXPOSURE_TO_ANCHOR",
    "macro": "MACRO_IMPACT_ON_ANCHOR",
    "regulatory": "REGULATORY_IMPACT_ON_ANCHOR",
    "market_sentiment": "MARKET_SENTIMENT_IMPACT_ON_ANCHOR",
    "mentioned": "MENTIONS_ANCHOR_COMPANY",
    "other": "RELATED_TO_ANCHOR",
}

EVENT_TIME_ROLES = {
    "occurrence_date",
    "reported_period",
    "measurement_window",
    "guidance_period",
    "deadline",
    "future_effective_period",
    "announcement_date",
    "historical_event",
    "unknown",
}

EVENT_TIME_GRANULARITIES = {"day", "month", "quarter", "year", "range", "unknown"}
PERIOD_EVENT_TIME_ROLES = {
    "reported_period",
    "measurement_window",
    "guidance_period",
    "future_effective_period",
}

MIRRORED_RELATION_DEDUPE_EVENT_TYPES = {
    "supply_chain_event",
    "competitive_position",
    "partnership",
    "business_segment_performance",
    "market_commentary",
}

EVENT_TEMPORAL_COLUMNS = [
    "article_date",
    "available_date",
    "event_date_start",
    "event_date_end",
    "event_time_role",
    "event_time_granularity",
    "event_time_source",
    "event_time_confidence",
    "event_time_normalizer",
    "event_time_json",
]
